# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .

formats:
  - htmlzip
  - pdf
  - epub

# Build PDF & ePub
sphinx:
  builder: html
  configuration: docs/source/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs/source/requirements.txt